-------------- SQL TEST ------------------

-------- 1)Requête simple

WITH DAYS AS (
SELECT * FROM UNNEST(GENERATE_DATE_ARRAY(DATE('2020-01-01'), DATE('2020-12-31'))) AS DAY
LEFT JOIN `SQL_TESTTRANSACTOIN` AS T
ON DAY = T.DATE
)

SELECT DAY AS DATE, COALESCE(SUM(PROD_PRICE*PROD_QTY),0) AS VENTES
FROM DAYS
GROUP BY DATE
ORDER BY 1
;


-------- 2) Requête complexe:
WITH SQ AS (
  SELECT 
    T.CLIENT_ID,
    P.PRODUCT_TYPE,
    SUM(T.PROD_PRICE * T.PROD_QTY) AS VENTES
  FROM
    `SQL_TEST.TRANSACTOIN` AS T
  JOIN `SQL_TEST.PRODUCT_NOMENCLATURE` AS P
  ON T.PROD_ID = P.PRODUCT_ID
  WHERE T.DATE BETWEEN '2020-01-01' AND '2020-12-31'
  GROUP BY T.CLIENT_ID, P.PRODUCT_TYPE
)

SELECT CLIENT_ID, COALESCE(MEUBLE,0), COALESCE(DECO,0) FROM SQ
PIVOT(SUM(VENTES) FOR PRODUCT_TYPE IN ('MEUBLE', 'DECO'))
